//! Low-level FFI bindings to minibwa. Generated by bindgen; see `build.rs`.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
